#!/usr/bin/env python3
"""
Demo script showing how to use the test framework for DICOM PDF processing.
This script demonstrates the key features without requiring actual Orthanc connection.
"""

import os
import sys
import tempfile
import json
from datetime import datetime

# Add project root to path
ROOT_DIR = os.path.abspath(os.path.dirname(__file__))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from config import config
from test_utils import TestLogger, FileValidator, TestReporter


def demo_logging():
    """Demonstrate logging functionality."""
    print("=" * 60)
    print("DEMO: Logging Functionality")
    print("=" * 60)
    
    logger = TestLogger("DemoLogger")
    
    logger.info("Starting demo of logging system")
    logger.step("Demo Step 1", "STARTED")
    logger.debug("This is a debug message")
    logger.warning("This is a warning message")
    logger.step("Demo Step 1", "COMPLETED")
    logger.error("This is an error message (for demo purposes)")
    
    print("\n✓ Logging demo completed - check test_results/test_execution.log for full log")


def demo_configuration():
    """Demonstrate configuration management."""
    print("\n" + "=" * 60)
    print("DEMO: Configuration Management")
    print("=" * 60)
    
    config.print_configuration()
    
    print("\nEnvironment validation:")
    validation_result = config.validate_environment()
    
    print(f"Valid: {validation_result['valid']}")
    print(f"Missing dependencies: {validation_result['missing_dependencies']}")
    print(f"Missing configurations: {validation_result['missing_configurations']}")
    print(f"Warnings: {len(validation_result['warnings'])}")
    
    for warning in validation_result['warnings']:
        print(f"  - {warning}")
    
    print("\n✓ Configuration demo completed")


def demo_file_validation():
    """Demonstrate file validation functionality."""
    print("\n" + "=" * 60)
    print("DEMO: File Validation")
    print("=" * 60)
    
    logger = TestLogger("DemoFileValidator")
    validator = FileValidator(logger)
    
    # Create temporary patient structure for demo
    patient_name = "DemoPatient"
    patient_dirs = config.get_patient_directories(patient_name)
    
    # Create directories
    for dir_path in patient_dirs.values():
        os.makedirs(dir_path, exist_ok=True)
    
    # Create some demo files
    demo_files = {
        os.path.join(patient_dirs["images"], "demo_image.jpeg"): "fake jpeg content",
        os.path.join(patient_dirs["reports"], f"{patient_name}_ocr.txt"): "Demo OCR content extracted from images",
        os.path.join(patient_dirs["reports"], f"{patient_name}_report.txt"): "Demo medical report generated by AI",
        os.path.join(patient_dirs["reports"], f"{patient_name}.pdf"): "fake pdf content"
    }
    
    for file_path, content in demo_files.items():
        with open(file_path, 'w') as f:
            f.write(content)
    
    print(f"Created demo patient structure for: {patient_name}")
    
    # Validate structure
    validation_result = validator.validate_patient_structure(patient_name)
    
    print(f"\nValidation results:")
    print(f"Validation passed: {validation_result['validation_passed']}")
    print(f"Issues found: {len(validation_result['issues'])}")
    
    for issue in validation_result['issues']:
        print(f"  - {issue}")
    
    print(f"\nDirectories found:")
    for dir_type, dir_info in validation_result['directories'].items():
        print(f"  - {dir_type}: {dir_info['exists']}")
    
    print(f"\nFiles found:")
    for file_type, file_info in validation_result['files'].items():
        print(f"  - {file_type}: {file_info['count']} files")
    
    print("\n✓ File validation demo completed")


def demo_test_reporting():
    """Demonstrate test reporting functionality."""
    print("\n" + "=" * 60)
    print("DEMO: Test Reporting")
    print("=" * 60)
    
    logger = TestLogger("DemoReporter")
    reporter = TestReporter(logger)
    
    # Create demo test results
    demo_results = {
        "test_session": {
            "started": datetime.now().isoformat(),
            "completed": datetime.now().isoformat(),
            "duration": "00:05:30",
            "configuration": {
                "orthanc_host": "demo.orthanc.server",
                "openai_configured": True,
                "test_results_dir": config.test_results_dir
            }
        },
        "tests": [
            {
                "name": "Environment Validation",
                "passed": True,
                "timestamp": datetime.now().isoformat(),
                "issues": []
            },
            {
                "name": "Orthanc Connection",
                "passed": True,
                "timestamp": datetime.now().isoformat(),
                "issues": []
            },
            {
                "name": "Patient Processing - Demo Patient",
                "passed": True,
                "timestamp": datetime.now().isoformat(),
                "issues": []
            },
            {
                "name": "File Validation - Demo Patient",
                "passed": False,
                "timestamp": datetime.now().isoformat(),
                "issues": ["PDF file suspiciously small"]
            }
        ]
    }
    
    # Generate report
    report_path = reporter.generate_test_report(demo_results)
    
    print(f"Test report generated at: {report_path}")
    
    # Print summary
    reporter.print_test_summary(demo_results)
    
    print("\n✓ Test reporting demo completed")


def demo_patient_directory_structure():
    """Demonstrate the expected directory structure."""
    print("\n" + "=" * 60)
    print("DEMO: Patient Directory Structure")
    print("=" * 60)
    
    patients = ["Patient_A", "Patient_B", "Patient_C"]
    
    print("Expected directory structure:")
    print("test_results/")
    print("├── Pacientes/")
    
    for i, patient in enumerate(patients):
        if i == len(patients) - 1:
            print(f"│   └── {patient}/")
            print(f"│       ├── Images/")
            print(f"│       │   ├── {patient}0.jpeg")
            print(f"│       │   ├── {patient}1.jpeg")
            print(f"│       │   └── ...")
            print(f"│       └── Report/")
            print(f"│           ├── {patient}_ocr.txt")
            print(f"│           ├── {patient}_report.txt")
            print(f"│           └── {patient}.pdf")
        else:
            print(f"│   ├── {patient}/")
            print(f"│   │   ├── Images/")
            print(f"│   │   └── Report/")
    
    print("├── ZIPS/")
    print("│   ├── patient_id_1.zip")
    print("│   ├── patient_id_2.zip")
    print("│   └── ...")
    print("├── Dicoms/")
    print("│   └── [temporary_files]")
    print("├── test_execution.log")
    print("└── test_report.json")
    
    print("\n✓ Directory structure demo completed")


def main():
    """Run all demo functions."""
    print("🎯 DICOM PDF Test Framework Demo")
    print("This demo shows the key features of the test framework.\n")
    
    # Setup configuration
    config.setup_directories()
    
    # Run demos
    demo_logging()
    demo_configuration()
    demo_file_validation()
    demo_test_reporting()
    demo_patient_directory_structure()
    
    print("\n" + "=" * 60)
    print("✨ DEMO COMPLETED")
    print("=" * 60)
    print("The test framework is ready to use with real Orthanc data.")
    print("To use with actual data:")
    print("1. Configure environment variables (ORTHANC_HOST, OPENAI_API_KEY)")
    print("2. Run: python test_single_patient.py")
    print("3. Select a patient from the interactive list")
    print("4. Review results in test_results/ directory")
    print("\nFor more details, see TEST_README.md")


if __name__ == "__main__":
    main()