name: dicom-pdf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flake8
  - pytest
  - pydicom
  - pillow
  - numpy
  - reportlab
  - pip:
      - requests
      - -r requirements.txt
