name: dicom-pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pydicom
  - pillow
  - numpy
  - matplotlib
  - reportlab
  - opencv
  - pytesseract
  - scipy
  - rich
  - tabulate
  - pip:
      - pyorthanc
      - fpdf
      - openai
