name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug environment.yml
      run: |
        echo "=== Verificando se o arquivo existe ==="
        ls -la environment.yml
        echo ""
        echo "=== Conteúdo do environment.yml ==="
        cat environment.yml
        echo ""
        echo "=== Verificando caracteres especiais e encoding ==="
        file environment.yml
        echo ""
        echo "=== Mostrando caracteres não-imprimíveis ==="
        cat -A environment.yml
        echo ""
        echo "=== Validando YAML ==="
        python -c "import yaml; yaml.safe_load(open('environment.yml'))" && echo "YAML válido!" || echo "YAML inválido!"
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: dicom-pdf
        environment-file: environment.yml
        auto-activate-base: false
    
    - name: Display Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
        python --version
        which python
    
    - name: Install additional test dependencies
      shell: bash -l {0}
      run: |
        conda install -n dicom-pdf flake8 pytest -y
    
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # Para de buildar se tiver erros de sintaxe Python ou nomes indefinidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero trata todos os erros como warnings. O editor do GitHub tem 127 chars de largura
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest -v
